#!/usr/bin/env pwsh
# Build ChallaChat Windows installer using Inno Setup
# Produces build\challachat-setup.exe

$ErrorActionPreference = 'Stop'

function Run($cmd) {
  Write-Host "Running: $cmd" -ForegroundColor Cyan
  $p = Start-Process -FilePath "cmd.exe" -ArgumentList "/c $cmd" -NoNewWindow -Wait -PassThru
  if ($p.ExitCode -ne 0) { throw "Command failed with exit code $($p.ExitCode): $cmd" }
}

$ScriptDir = $PSScriptRoot
$RootDir = Split-Path -Parent (Split-Path -Parent $ScriptDir)
Set-Location -Path $RootDir

Write-Host "=================================" -ForegroundColor Magenta
Write-Host " ChallaChat - Installer Builder" -ForegroundColor Magenta
Write-Host "=================================" -ForegroundColor Magenta
Write-Host ""

# Check for Inno Setup
$iscc = (Get-Command iscc.exe -ErrorAction SilentlyContinue)
if (-not $iscc) {
  Write-Warning "Inno Setup not found on PATH. Install from https://jrsoftware.org/isinfo.php or via choco install innosetup"
  if ($env:GITHUB_ACTIONS -eq 'true' -or $env:CI -eq 'true') {
    throw "Inno Setup is required in CI to build the installer. Ensure iscc.exe is on PATH."
  }
  Write-Warning "Skipping installer build. Payload will still be created."
}

# First, build the portable payload
Write-Host "Building portable payload..." -ForegroundColor Yellow
Run "npm run build:portable"

$payloadDir = "build/challachat-portable"
if (-not (Test-Path $payloadDir)) {
  throw "Portable build failed - payload directory not found: $payloadDir"
}

# Get version from package.json
$packageJson = Get-Content "package.json" | ConvertFrom-Json
$version = $packageJson.version
Write-Host "Building installer for version: $version" -ForegroundColor Cyan

# Create Inno Setup script
$issDir = Join-Path $ScriptDir "inno"
New-Item -ItemType Directory -Path $issDir -ErrorAction SilentlyContinue | Out-Null

$issScript = @"
; ChallaChat Installer Script for Inno Setup
; Generated by build-installer.ps1

#define MyAppName "ChallaChat"
#define MyAppVersion "$version"
#define MyAppPublisher "Challacade"
#define MyAppURL "https://github.com/challacade/challachat"
#define MyAppExeName "challachat.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
AppId={{2F3C9F2B-8C91-4A20-9B8E-5A2E5C8C1A44}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
LicenseFile=
OutputDir=..\..\..\build
OutputBaseFilename=challachat-setup
Compression=lzma
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=admin
ArchitecturesAllowed=x64compatible

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "..\..\..\build\challachat-portable\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
Type: filesandordirs; Name: "{app}"
"@

$issFile = Join-Path $issDir "challachat.iss"
Set-Content -Path $issFile -Value $issScript

# Build installer with Inno Setup
if ($iscc) {
  Write-Host "Compiling installer with Inno Setup..." -ForegroundColor Yellow
  $installerOutput = Join-Path $RootDir "build\challachat-setup.exe"
  
  # Remove old installer if exists
  if (Test-Path $installerOutput) {
    Remove-Item $installerOutput -Force
  }
  
  Run "iscc `"$issFile`""
  
  if (Test-Path $installerOutput) {
    $installerSize = (Get-Item $installerOutput).Length / 1MB
    Write-Host ""
    Write-Host "=================================" -ForegroundColor Green
    Write-Host "Installer build complete!" -ForegroundColor Green
    Write-Host "=================================" -ForegroundColor Green
    Write-Host ""
    Write-Host "Installer: build\challachat-setup.exe ($([math]::Round($installerSize,1)) MB)" -ForegroundColor Cyan
    Write-Host ""
  } else {
    throw "Installer compilation failed - output file not found"
  }
} else {
  Write-Warning "Inno Setup not available; installer not built. Payload is available at $payloadDir."
}

# Clean up
Write-Host "Cleaning up... " -ForegroundColor Yellow -NoNewline
Remove-Item $issFile -Force -ErrorAction SilentlyContinue
if (Test-Path $issDir) {
  Remove-Item $issDir -Recurse -Force -ErrorAction SilentlyContinue
}
Write-Host "Done!" -ForegroundColor Yellow
